"""Seed catalog data for tours, taxi services and rental vehicles.
Imported by server.py at startup — the data itself is a plain Python constant,
so keeping it in a separate module avoids clutter and makes edits safer.
"""
from typing import Dict, List, Set


TOURS_SEED: List[Dict] = [
    {"id": "blue-lagoon", "name": "Blue Lagoon Island Beach Day", "price": 89.0, "duration": "6 hours",
     "location": "Departs Nassau Harbour", "featured": True,
     "description": "A quick ferry from Nassau lands you on a private-feel island — hammocks, kayaks, snorkeling and a rum punch bar.",
     "image_url": "https://images.unsplash.com/photo-1723567017685-86060d4861c7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzR8MHwxfHNlYXJjaHwyfHxiYWhhbWFzJTIwYmVhY2glMjBjbGVhciUyMHdhdGVyfGVufDB8fHx8MTc4NTA2MjgxMXww&ixlib=rb-4.1.0&q=85",
     "category": "excursion", "active": True},
    {"id": "atlantis-tour", "name": "Paradise Island & Atlantis City Tour", "price": 45.0, "duration": "3 hours",
     "location": "Paradise Island", "featured": True,
     "description": "Guided city tour ending at Atlantis Resort with photo stops at Fort Fincastle, Queen's Staircase and the Cloisters.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85",
     "category": "tour", "active": True},
    {"id": "snorkel-rose", "name": "Rose Island Reef Snorkeling", "price": 65.0, "duration": "4 hours",
     "location": "Departs Paradise Island", "featured": True,
     "description": "Just off Paradise Island — vibrant reef gardens, sea turtles and rum punch on the ride back.",
     "image_url": "https://images.unsplash.com/photo-1680635601834-581581c6cdfa?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwyfHxzbm9ya2VsaW5nJTIwYmFoYW1hcyUyMGNsZWFyJTIwd2F0ZXJ8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85",
     "category": "excursion", "active": True},
    {"id": "island-hop", "name": "Three-Island Boat Hopping (from Nassau)", "price": 149.0, "duration": "7 hours",
     "location": "Departs Nassau", "featured": False,
     "description": "Cruise Nassau's out-islands with beach stops, lunch, and unlimited drinks.",
     "image_url": "https://images.pexels.com/photos/4166305/pexels-photo-4166305.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
     "category": "excursion", "active": True},
]

TAXI_SERVICES: List[Dict] = [
    {"id": "airport-nassau", "name": "LPIA Airport → Downtown Nassau / Cable Beach", "price": 35.0,
     "route": "LPIA → Nassau", "featured": True,
     "description": "Flat rate per taxi, up to 3 passengers. Meet & greet at arrivals, luggage help, air-conditioned.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85"},
    {"id": "airport-paradise", "name": "LPIA Airport → Paradise Island / Atlantis / Baha Mar", "price": 45.0,
     "route": "LPIA → Paradise Island", "featured": True,
     "description": "Flat rate per taxi, up to 3 passengers. Paradise Island bridge toll included.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85"},
    {"id": "port-paradise", "name": "Cruise Port (Prince George Wharf) → Paradise Island", "price": 25.0,
     "route": "Cruise Port → Paradise Island", "featured": True,
     "description": "Straight from the ship to your Paradise Island resort. Bridge toll included.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85"},
    {"id": "paradise-nassau", "name": "Paradise Island ↔ Downtown Nassau Shuttle", "price": 20.0,
     "route": "Paradise Island ↔ Nassau", "featured": True,
     "description": "Bay Street shopping, Fish Fry dinner, downtown nightlife — cross the bridge with ease.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85"},
    {"id": "hourly-charter", "name": "Nassau / Paradise Island Hourly Charter", "price": 55.0,
     "route": "By the hour", "featured": False,
     "description": "Private driver by the hour, 2-hour minimum. Perfect for shopping, sightseeing, or errands.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85"},
    {"id": "van-group", "name": "Group Van Transfer (up to 8 pax) — Nassau + Paradise Island", "price": 90.0,
     "route": "Anywhere on Nassau / PI", "featured": False,
     "description": "Weddings, families, cruise groups. Airport, hotel, cruise port pickups & drop-offs.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85"},
    {"id": "airport-bahamar", "name": "LPIA Airport → Baha Mar / SLS / Grand Hyatt", "price": 35.0,
     "route": "LPIA → Baha Mar", "featured": True,
     "description": "Fixed rate to the Baha Mar resort complex on Cable Beach. Up to 3 passengers.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "cablebeach-downtown", "name": "Cable Beach ↔ Downtown Nassau (Bay Street)", "price": 18.0,
     "route": "Cable Beach ↔ Downtown", "featured": False,
     "description": "Quick hop between Cable Beach hotels and Bay Street shopping / straw market. Nassau tariff.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "downtown-paradise", "name": "Downtown Nassau → Paradise Island (via bridge)", "price": 12.0,
     "route": "Downtown → Paradise Island", "featured": False,
     "description": "Includes $1 Paradise Island bridge toll. Standard Nassau tariff for up to 2 passengers.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "cablebeach-atlantis", "name": "Cable Beach ↔ Atlantis / Paradise Island", "price": 30.0,
     "route": "Cable Beach ↔ Atlantis", "featured": False,
     "description": "Cross-island transfer including bridge toll. Popular for dinner + casino runs.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "fish-fry-shuttle", "name": "Hotel → Arawak Cay Fish Fry (evening)", "price": 15.0,
     "route": "Any Nassau hotel → Fish Fry", "featured": False,
     "description": "One-way evening ride to Nassau's iconic Fish Fry food strip. Return quote on request.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "compass-point", "name": "Nassau → Compass Point / West Bay Street", "price": 25.0,
     "route": "Nassau → West Bay", "featured": False,
     "description": "West-side beach clubs and restaurants beyond Cable Beach. Fixed one-way rate.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "adelaide-southwest", "name": "Nassau → Adelaide Village / South West", "price": 50.0,
     "route": "Nassau → Adelaide", "featured": False,
     "description": "Long-distance transfer to Adelaide Village and the south-west coast. Per Nassau tariff.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
    {"id": "blue-hole-roundtrip", "name": "Nassau → Blue Hole / Lyford Cay (round trip)", "price": 80.0,
     "route": "Nassau ↔ Lyford Cay", "featured": False,
     "description": "Round-trip driver waits up to 90 min. Great for beach picnics or Lyford visits.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"},
]

RENTALS_SEED: List[Dict] = [
    {"id": "spark-compact", "name": "2019 Chevrolet Spark — Compact", "price": 45.0, "seats": 4,
     "year": 2019, "make": "Chevrolet", "model": "Spark", "color": "Silver", "body": "Compact",
     "description": "Zippy little compact — perfect for solo travelers and couples buzzing around Nassau. AC, automatic, unlimited miles. Free delivery to LPIA or your hotel.",
     "image_url": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
     "category": "compact", "active": True},
    {"id": "sentra-orange", "name": "2001 Nissan Sentra — Orange Sedan", "price": 39.0, "seats": 5,
     "year": 2001, "make": "Nissan", "model": "Sentra", "color": "Orange", "body": "Sedan",
     "description": "Old but reliable island cruiser — the ultimate budget rental. Bright orange, hard to lose in a parking lot. Free Nassau delivery.",
     "image_url": "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
     "category": "economy", "active": True},
    {"id": "malibu-fullsize", "name": "2019 Chevrolet Malibu — Full-Size Sedan (White)", "price": 79.0, "seats": 5,
     "year": 2019, "make": "Chevrolet", "model": "Malibu", "color": "White", "body": "Full-size Sedan",
     "description": "Spacious full-size sedan for comfort on longer Bahamas drives. Bluetooth, backup camera, roomy trunk.",
     "image_url": "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
     "category": "full-size", "active": True},
    {"id": "trax-suv", "name": "2025 Chevrolet Trax — SUV (White)", "price": 119.0, "seats": 5,
     "year": 2025, "make": "Chevrolet", "model": "Trax", "color": "White", "body": "SUV",
     "description": "Brand-new 2025 SUV with clearance for out-of-town beach runs and cargo for the whole crew. Apple CarPlay, backup cam, roof rack.",
     "image_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
     "category": "suv", "active": True},
    {"id": "town-country-van", "name": "2022 Chrysler Town & Country — Mini-Van (White)", "price": 149.0, "seats": 7,
     "year": 2022, "make": "Chrysler", "model": "Town & Country", "color": "White", "body": "Mini-Van",
     "description": "Family & group hauler — 7 seats, sliding doors, panoramic space. Perfect for cruise-port pickups and family beach days.",
     "image_url": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
     "category": "mini-van", "active": True},
]

CURRENT_RENTAL_IDS: Set[str] = {r["id"] for r in RENTALS_SEED}
