"""Seed catalog data for tours, taxi services and rental vehicles.
Imported by server.py at startup — the data itself is a plain Python constant,
so keeping it in a separate module avoids clutter and makes edits safer.
"""
from typing import Any, Dict, List, Set


TOURS_SEED: List[Dict] = [
    {"id": "blue-lagoon", "name": "Blue Lagoon Island Beach Day", "price": 89.0, "duration": "6 hours",
     "location": "Departs Nassau Harbour", "featured": True,
     "description": "A quick ferry from Nassau lands you on a private-feel island — hammocks, kayaks, snorkeling and a rum punch bar.",
     "image_url": "https://images.unsplash.com/photo-1723567017685-86060d4861c7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2NzR8MHwxfHNlYXJjaHwyfHxiYWhhbWFzJTIwYmVhY2glMjBjbGVhciUyMHdhdGVyfGVufDB8fHx8MTc4NTA2MjgxMXww&ixlib=rb-4.1.0&q=85",
     "category": "excursion", "active": True},
    {"id": "atlantis-tour", "name": "Paradise Island & Atlantis City Tour", "price": 45.0, "duration": "3 hours",
     "location": "Paradise Island", "featured": True,
     "description": "Guided city tour ending at Atlantis Resort with photo stops at Fort Fincastle, Queen's Staircase and the Cloisters.",
     "image_url": "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzdXYlMjBkcml2aW5nJTIwdHJvcGljYWx8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85",
     "category": "tour", "active": True},
    {"id": "snorkel-rose", "name": "Rose Island Reef Snorkeling", "price": 65.0, "duration": "4 hours",
     "location": "Departs Paradise Island", "featured": True,
     "description": "Just off Paradise Island — vibrant reef gardens, sea turtles and rum punch on the ride back.",
     "image_url": "https://images.unsplash.com/photo-1680635601834-581581c6cdfa?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwyfHxzbm9ya2VsaW5nJTIwYmFoYW1hcyUyMGNsZWFyJTIwd2F0ZXJ8ZW58MHx8fHwxNzg1MDYyODExfDA&ixlib=rb-4.1.0&q=85",
     "category": "excursion", "active": True},
    {"id": "island-hop", "name": "Three-Island Boat Hopping (from Nassau)", "price": 149.0, "duration": "7 hours",
     "location": "Departs Nassau", "featured": False,
     "description": "Cruise Nassau's out-islands with beach stops, lunch, and unlimited drinks.",
     "image_url": "https://images.pexels.com/photos/4166305/pexels-photo-4166305.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
     "category": "excursion", "active": True},
    {"id": "jet-ski-1hr", "name": "Jet Ski Rental — 1 Hour (Cabbage Beach / Paradise Island)", "price": 120.0, "duration": "1 hour",
     "location": "Cabbage Beach, Paradise Island", "featured": True,
     "description": "Rip across turquoise water on a modern jet ski — up to 2 riders per ski. Life vests, safety briefing and beach launch included. Book direct with our partner operator.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/necxwdup_CASMJETSKIANDBEACH-2.jpg",
     "category": "watersport", "active": True,
     "external_booking_url": "https://www.viator.com/tours/Nassau/Jet-ski/d420-230576P1"},
    {"id": "jet-ski-30min", "name": "Jet Ski Rental — 30 Minutes (Nassau)", "price": 99.0, "duration": "30 minutes",
     "location": "Nassau — beach launch", "featured": False,
     "description": "Quick-hit jet ski blast — perfect if your cruise ship is only in port for the day. Single or tandem, life vests included.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/0trvjsor_pine-cay-jet-ski-tour.jpg",
     "category": "watersport", "active": True,
     "external_booking_url": "https://www.kcwatersportsbahamas.com/jetskirentals"},
    {"id": "atv-tour-lunch", "name": "ATV Off-Road Tour of Nassau & Paradise Island (with Lunch)", "price": 149.0, "duration": "3 hours",
     "location": "Nassau — cruise-port pickup", "featured": True,
     "description": "Guided ATV convoy through Nassau's back-roads, coastal viewpoints and Paradise Island vistas. Bahamian lunch, helmet, gloves and cruise-port pickup included. Driver must be 25+.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/xkgd6xt4_images_atv.jpg",
     "category": "adventure", "active": True,
     "external_booking_url": "https://www.viator.com/tours/Nassau/3-Hour-2-passenger-ATV-Tour-of-Nassau-and-Paradise-Island-Inclusive-of-Lunch/d420-70706P11"},
    {"id": "atv-tour-2hr", "name": "ATV Off-Road Power Tour — 2 Hours (Cruise-Port Pickup)", "price": 122.0, "duration": "2 hours",
     "location": "Nassau — cruise-port pickup", "featured": False,
     "description": "Fast-paced 2-hour ATV ride with roundtrip cruise-port transport. Great for shore-excursion timing. Book direct with Bowcar Bahamas.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/w7ff6nbv_IMG-20250212-WA0083-1-scaled.webp",
     "category": "adventure", "active": True,
     "external_booking_url": "https://www.bowcarbahamas.com/tour/atv-tour/"},
]

# Nassau / New Providence official taxi tariff (posted at LPIA taxi rank + Ministry table).
# Prices are for the first 2 passengers. Each additional passenger: +$5.
# Paradise Island trips include the $2 bridge toll. Extra luggage: +$2.20 per piece.
# Sources: nassaulpia.com/to-from/taxis, bahamas-travel.info/taxi-fares, hopbahamas.com 2026 guide.
_TARIFF_NOTE = "Official Nassau tariff. First 2 passengers. +$5 per extra passenger. Paradise Island bridge toll ($2) included where applicable."
_TAXI_IMG = "https://images.unsplash.com/photo-1736742482023-03f3be60875e?crop=entropy&cs=srgb&fm=jpg&q=85"

TAXI_SERVICES: List[Dict] = [
    {"id": "airport-nassau", "name": "LPIA Airport → Downtown Nassau", "price": 40.0,
     "route": "LPIA → Downtown Nassau", "featured": True,
     "description": f"{_TARIFF_NOTE} Meet & greet at arrivals, luggage help, air-conditioned.",
     "image_url": _TAXI_IMG},
    {"id": "airport-cablebeach", "name": "LPIA Airport → Cable Beach", "price": 35.0,
     "route": "LPIA → Cable Beach", "featured": True,
     "description": f"{_TARIFF_NOTE} Includes SuperClubs Breezes, Melia, Sandals Royal Bahamian.",
     "image_url": _TAXI_IMG},
    {"id": "airport-bahamar", "name": "LPIA Airport → Baha Mar / SLS / Grand Hyatt / Rosewood", "price": 35.0,
     "route": "LPIA → Baha Mar", "featured": True,
     "description": f"{_TARIFF_NOTE} Baha Mar resort complex on Cable Beach.",
     "image_url": _TAXI_IMG},
    {"id": "airport-paradise", "name": "LPIA Airport → Paradise Island / Atlantis", "price": 45.0,
     "route": "LPIA → Paradise Island", "featured": True,
     "description": f"{_TARIFF_NOTE} Paradise Island $2 bridge toll included.",
     "image_url": _TAXI_IMG},
    {"id": "airport-cruiseport", "name": "LPIA Airport → Nassau Cruise Port (Festival Place)", "price": 38.0,
     "route": "LPIA → Cruise Port", "featured": True,
     "description": f"{_TARIFF_NOTE} Direct to Prince George Wharf for embarkation.",
     "image_url": _TAXI_IMG},
    {"id": "port-paradise", "name": "Nassau Cruise Port → Paradise Island / Atlantis", "price": 20.0,
     "route": "Cruise Port → Paradise Island", "featured": True,
     "description": f"{_TARIFF_NOTE} Bridge toll included.",
     "image_url": _TAXI_IMG},
    {"id": "port-bahamar", "name": "Nassau Cruise Port → Baha Mar / Cable Beach", "price": 22.0,
     "route": "Cruise Port → Baha Mar", "featured": True,
     "description": f"{_TARIFF_NOTE} Straight from Prince George Wharf to Cable Beach resorts.",
     "image_url": _TAXI_IMG},
    {"id": "downtown-paradise", "name": "Downtown Nassau ↔ Paradise Island", "price": 13.0,
     "route": "Downtown ↔ Paradise Island", "featured": True,
     "description": f"{_TARIFF_NOTE} Bay Street shopping, Fish Fry, Atlantis casino runs. Bridge toll included.",
     "image_url": _TAXI_IMG},
    {"id": "cablebeach-downtown", "name": "Cable Beach ↔ Downtown Nassau (Bay Street)", "price": 20.0,
     "route": "Cable Beach ↔ Downtown", "featured": True,
     "description": f"{_TARIFF_NOTE} Bay Street shopping / straw market from Cable Beach hotels.",
     "image_url": _TAXI_IMG},
    {"id": "bahamar-downtown", "name": "Baha Mar ↔ Downtown Nassau (Bay Street)", "price": 20.0,
     "route": "Baha Mar ↔ Downtown", "featured": True,
     "description": f"{_TARIFF_NOTE} Same tariff as Cable Beach ↔ Downtown.",
     "image_url": _TAXI_IMG},
    {"id": "cablebeach-atlantis", "name": "Cable Beach ↔ Atlantis / Paradise Island", "price": 30.0,
     "route": "Cable Beach ↔ Atlantis", "featured": False,
     "description": f"{_TARIFF_NOTE} Popular for dinner + casino runs. Bridge toll included.",
     "image_url": _TAXI_IMG},
    {"id": "bahamar-atlantis", "name": "Baha Mar ↔ Atlantis / Paradise Island", "price": 30.0,
     "route": "Baha Mar ↔ Atlantis", "featured": False,
     "description": f"{_TARIFF_NOTE} Bridge toll included.",
     "image_url": _TAXI_IMG},
    {"id": "hourly-charter", "name": "Nassau / Paradise Island Hourly Charter", "price": 55.0,
     "route": "By the hour (2-hour min)", "featured": False,
     "description": "Private driver by the hour, 2-hour minimum. Perfect for shopping, sightseeing, or errands.",
     "image_url": _TAXI_IMG},
    {"id": "van-group", "name": "Group Van Transfer (up to 8 pax) — Nassau + Paradise Island", "price": 90.0,
     "route": "Anywhere on Nassau / PI", "featured": False,
     "description": "Weddings, families, cruise groups. Airport, hotel, cruise port pickups & drop-offs.",
     "image_url": _TAXI_IMG},
    {"id": "fish-fry-shuttle", "name": "Any Nassau Hotel → Arawak Cay Fish Fry (evening)", "price": 15.0,
     "route": "Hotel → Fish Fry", "featured": False,
     "description": f"{_TARIFF_NOTE} One-way evening ride to Nassau's iconic Fish Fry food strip.",
     "image_url": _TAXI_IMG},
    {"id": "fishfry-downtown", "name": "Arawak Cay Fish Fry ↔ Downtown Nassau", "price": 20.0,
     "route": "Fish Fry ↔ Downtown", "featured": False,
     "description": f"{_TARIFF_NOTE} Short hop between Fish Fry food strip and Bay Street / Prince George Wharf.",
     "image_url": _TAXI_IMG},
    {"id": "fishfry-paradise", "name": "Arawak Cay Fish Fry → Paradise Island / Atlantis", "price": 25.0,
     "route": "Fish Fry → Paradise Island", "featured": False,
     "description": f"{_TARIFF_NOTE} Post-dinner ride from Fish Fry across the bridge to Paradise Island / Atlantis. Bridge toll auto-added on booking.",
     "image_url": _TAXI_IMG},
    {"id": "fishfry-bahamar", "name": "Arawak Cay Fish Fry → Baha Mar / Cable Beach", "price": 25.0,
     "route": "Fish Fry → Baha Mar / Cable Beach", "featured": False,
     "description": f"{_TARIFF_NOTE} Post-dinner ride from Fish Fry west along Cable Beach to Baha Mar / SLS / Grand Hyatt / Rosewood.",
     "image_url": _TAXI_IMG},
    {"id": "compass-point", "name": "Nassau → Compass Point / West Bay Street", "price": 25.0,
     "route": "Nassau → West Bay", "featured": False,
     "description": f"{_TARIFF_NOTE} West-side beach clubs and restaurants beyond Cable Beach.",
     "image_url": _TAXI_IMG},
    {"id": "adelaide-southwest", "name": "Nassau → Adelaide Village / South West", "price": 50.0,
     "route": "Nassau → Adelaide", "featured": False,
     "description": f"{_TARIFF_NOTE} Long-distance transfer to Adelaide Village and the south-west coast.",
     "image_url": _TAXI_IMG},
    {"id": "blue-hole-roundtrip", "name": "Nassau → Blue Hole / Lyford Cay (round trip)", "price": 80.0,
     "route": "Nassau ↔ Lyford Cay", "featured": False,
     "description": "Round-trip driver waits up to 90 min. Great for beach picnics or Lyford visits.",
     "image_url": _TAXI_IMG},
    {"id": "downtown-lyford", "name": "Downtown Nassau → Lyford Cay (one-way)", "price": 60.0,
     "route": "Downtown → Lyford Cay", "featured": False,
     "description": f"{_TARIFF_NOTE} West-side long-haul transfer to Lyford Cay estates. $60 for the first 2 passengers · +$5 each additional passenger.",
     "image_url": _TAXI_IMG},
    {"id": "grocery-run", "name": "Grocery Pick-Up & Drop-Off (hourly)", "price": 55.0,
     "route": "Hotel/Villa ↔ Supermarket (by the hour)", "featured": True,
     "description": "Private driver waits while you shop and helps load groceries. Billed at the standard $55/hr hourly charter rate — 1-hour minimum, then pro-rata after. Popular stops: Solomon's, Super Value, Robin Hood, Family Value, Cost Right (Cable Beach & Baha Mar villas).",
     "image_url": _TAXI_IMG},
]

RENTALS_SEED: List[Dict] = [
    {"id": "spark-compact", "name": "2019 Chevrolet Spark — Compact", "price": 65.0, "seats": 4,
     "year": 2019, "make": "Chevrolet", "model": "Spark", "color": "White", "body": "Compact",
     "description": "Zippy little compact — perfect for solo travelers and couples buzzing around Nassau. AC, automatic, unlimited miles. Free delivery to LPIA or your hotel.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/iyv8ywh8_spark.webp",
     "category": "compact", "active": True},
    {"id": "sentra-orange", "name": "2021 Nissan Versa — Orange Sedan", "price": 65.0, "seats": 5,
     "year": 2021, "make": "Nissan", "model": "Versa", "color": "Orange", "body": "Sedan",
     "description": "Sharp, modern orange sedan — great fuel economy and easy to spot in a Nassau parking lot. AC, automatic, backup camera. Free delivery to LPIA or your hotel.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/5ky5n279_Nissan%20Versa.webp",
     "category": "economy", "active": True},
    {"id": "malibu-fullsize", "name": "2024 Chevrolet Malibu — Full-Size Sedan (White)", "price": 79.0, "seats": 5,
     "year": 2024, "make": "Chevrolet", "model": "Malibu", "color": "White", "body": "Full-size Sedan",
     "description": "Spacious full-size sedan for comfort on longer Bahamas drives. Bluetooth, backup camera, roomy trunk.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/cmfv1j07_2024-chevrolet-malibu-summit-white-color.webp",
     "category": "full-size", "active": True},
    {"id": "trax-suv", "name": "2025 Chevrolet Trax — SUV (White)", "price": 115.0, "seats": 5,
     "year": 2025, "make": "Chevrolet", "model": "Trax", "color": "White", "body": "SUV",
     "description": "Brand-new 2025 SUV with clearance for out-of-town beach runs and cargo for the whole crew. Apple CarPlay, backup cam, roof rack.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/234w5zk7_image.webp",
     "category": "suv", "active": True},
    {"id": "town-country-van", "name": "2022 Chrysler Town & Country — Mini-Van (White)", "price": 120.0, "seats": 7,
     "year": 2022, "make": "Chrysler", "model": "Town & Country", "color": "White", "body": "Mini-Van",
     "description": "Family & group hauler — 7 seats, sliding doors, panoramic space. Perfect for cruise-port pickups and family beach days.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/7y8bashr_pacifica.webp",
     "category": "mini-van", "active": True},
    {"id": "silverado-truck", "name": "2023 Chevrolet Silverado — Pickup Truck (White)", "price": 169.0, "seats": 5,
     "year": 2023, "make": "Chevrolet", "model": "Silverado", "color": "White", "body": "Pickup Truck",
     "description": "Full-size pickup for hauling gear, jet skis, or a big family run. Crew cab, tow package, backup camera, Bluetooth, and a bed cover keep your beach kit dry.",
     "image_url": "https://customer-assets-gfyr7b9c.emergentagent.net/job_bahamas-taxi-tours/artifacts/yk10r0dn_2022-Chevy-Silverado-1500-840-728x400.webp",
     "category": "truck", "active": True},
]

CURRENT_RENTAL_IDS: Set[str] = {r["id"] for r in RENTALS_SEED}


# Home page hero carousel — Nassau + Paradise Island rotating slides.
# `order` controls display sequence; `active` lets admin hide a slide
# without deleting it. Admin can edit / add / remove from /admin/manage.
HOME_SLIDES_SEED: List[Dict[str, Any]] = [
    {"id": "hero-nassau",     "title": "Unlock Nassau.",             "subtitle": "Book a taxi, tour or rental in sixty seconds.",
     "image_url": "https://images.unsplash.com/photo-1723567017685-86060d4861c7?crop=entropy&cs=srgb&fm=jpg&q=85&w=2400", "order": 1, "active": True},
    {"id": "hero-atlantis",   "title": "Atlantis, direct.",           "subtitle": "Paradise Island transfers in minutes.",
     "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/BHA_Nassau%2C_Paradise_Island%2C_Atlantis_Bridge_001.jpg/1920px-BHA_Nassau%2C_Paradise_Island%2C_Atlantis_Bridge_001.jpg", "order": 2, "active": True},
    {"id": "hero-rose-island","title": "Rose Island reefs.",          "subtitle": "Snorkel gardens twenty minutes off Nassau.",
     "image_url": "https://images.unsplash.com/photo-1544551763-46a013bb70d5?crop=entropy&cs=srgb&fm=jpg&q=85&w=2400", "order": 3, "active": True},
    {"id": "hero-junkanoo",   "title": "Junkanoo golden hour.",       "subtitle": "Cable Beach, Cabbage Beach, hidden coves — you pick.",
     "image_url": "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?crop=entropy&cs=srgb&fm=jpg&q=85&w=2400", "order": 4, "active": True},
    {"id": "hero-fish-fry",   "title": "Fish Fry, Arawak Cay.",       "subtitle": "Conch salad, cracked lobster, sky-blue punch.",
     "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=srgb&fm=jpg&q=85&w=2400", "order": 5, "active": True},
    {"id": "hero-exuma",      "title": "Exuma swimming pigs.",        "subtitle": "The famous day-trip, curated by local captains.",
     "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Vorobek_Bahamas_-_swimming_pigs.jpg/1920px-Vorobek_Bahamas_-_swimming_pigs.jpg", "order": 6, "active": True},
    {"id": "hero-straw",      "title": "Straw Market & Bay Street.",  "subtitle": "Colonial architecture, hand-woven souvenirs, hot patties.",
     "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Straw_Market_Nassau_Bahamas_2024.jpg/1920px-Straw_Market_Nassau_Bahamas_2024.jpg", "order": 7, "active": True},
    {"id": "hero-fort-charlotte", "title": "Fort Charlotte.",         "subtitle": "200-year-old British fortress overlooking Nassau Harbour — cannons, dungeons, panoramic views.",
     "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Fort_Charlotte%2C_Nassau%2C_The_Bahamas.jpg/1920px-Fort_Charlotte%2C_Nassau%2C_The_Bahamas.jpg", "order": 8, "active": True},
    {"id": "hero-baha-mar",   "title": "Baha Mar Resort.",            "subtitle": "Cable Beach — casino, Rosewood, SLS + a Jack Nicklaus golf course.",
     "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Reflection_-_panoramio_%2857%29.jpg/1920px-Reflection_-_panoramio_%2857%29.jpg",
     "link_url": "https://www.bahamar.com/", "link_label": "Book at Baha Mar", "order": 9, "active": True},
]
